[project]
name = "data-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "RAMANDEEP KAUR SAINI", email = "95361065+ramandeep-12@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
]

[project.scripts]
data-engineering = "data_engineering:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
