[project]
name = "pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "RAMANDEEP KAUR SAINI", email = "95361065+ramandeep-12@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "psycopg2-binary>=2.9.13",
    "pyarrow>=22.0.0",
    "sqlalchemy>=2.1.1",
    "tqdm>=4.70.1",
]

[project.scripts]
pipeline = "pipeline:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pgcli>=4.7.1",
]
